### ISSUE TITLE
API to check email receipt

### ISSUE THREAD

**Issue by somada141** [ThiefMaster/maildump#16]
Hi there and thank you for your wonderful project/port.

I've been developing a application meant to send notifications via email (Mailgun) and I was hoping to use Maildump for unit-testing. 

However, I wanted to ask: Is there a programmatic way to check email receipt? Would it be possible to add a RESTful API to Maildump that will retrieve emails based on something like a header value, subject, sender, etc? This way I could send emails with a given ID or subject and then poll Maildump from the unit test to check whether the email ever arrived.

I apologise if its already possible but I didn't see anything to suggest its feasible.

Thanks!

**Comment by ThiefMaster** [comment]
Since the frontend is pretty much pure javascript you can probably use the already existing RESTful API used by it. Check the endpoints in [web.py](https://github.com/ThiefMaster/maildump/blob/master/maildump/web.py).

I guess the easiest solution would be to delete all existing mails using `DELETE /messages/` right before running a test. Then you can get the full message list afterwards and won't have clutter from other tests.

---

But... for unit-tests it's usually easier if you use something like [pytest-localserver](https://pypi.python.org/pypi/pytest-localserver) which handles everything internally and gives you easy access to the mails without running a separate application.

**Comment by somada141** [comment]
Thanks a lot for the response!

You're probably right about the local test-server, however, I was hoping to use Maildump both as a single-node test-server during unit-tests as well as a larger-scale test/monitoring endpoint as a sanity check down the road when my code is deployed on several nodes/processes, e.g., through Celery.

Thanks again! I'll look into pytest-localserver first :D
